# Generated by Django 4.0.3 on 2022-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogpost_image_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Resim'),
        ),
    ]
