# Generated by Django 4.0.3 on 2022-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Resim')),
                ('text', models.TextField(max_length=200, verbose_name='Hakkımda')),
            ],
        ),
    ]
